services:
  app:
    command: [ "npm", "run", "${ENTRY}" ]
    user: ${TYPE}
    build:
      dockerfile: Dockerfile
      context: .
      target: development-stage-$TYPE-user
      args:
        - UID=$UID
    volumes:
      - .:/app
    ports:
      # app port
      - 9000:9000
    depends_on:
      - api

  api:
    extends:
      file: ../backend/docker-compose.yml
      service: api
    depends_on:
      - database

  database:
    extends:
      file: ../backend/docker-compose.yml
      service: database

volumes:
  postgres:
    name: database
