services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: development-stage
      args:
        - UID=$UID
    volumes:
      - .:/app
    ports:
      # app port
      - 9000:9000

  api:
    extends:
      file: ../backend/docker-compose.yml
      service: api

  database:
    extends:
      file: ../backend/docker-compose.yml
      service: database

volumes:
  postgres:
    name: database
