services:
  app:
    command: [ "npm", "run", "${ENTRY}" ]
    user: ${TYPE}
    environment:
      - HOME=/app/.cache
      - CYPRESS_CACHE_FOLDER=/app/.cache
      - API=http://api:3000
    build:
      dockerfile: Dockerfile
      context: .
      target: "development-stage-${TYPE}-user"
      args:
        - UID=$UID
    volumes:
      - .:/app
    ports:
      # app port
      - 9000:9000
    networks:
      - bingewatch-dev-net

networks:
  bingewatch-dev-net:
    name: bingewatch-dev-net
