FROM node:18.4.0 AS build-stage

WORKDIR /app

COPY ./*.config.js ./
COPY ./.eslint* ./
COPY index.html index.html

COPY *.json ./
RUN npm ci

COPY ./src ./src
COPY ./public ./public
RUN npm run build



FROM nginx:1.23.0-alpine AS production-stage

COPY --from=build-stage /app/dist/spa /usr/share/nginx/html

EXPOSE 80
EXPOSE 443
ENTRYPOINT ["nginx", "-g", "daemon off;"]
