FROM node:18.1.0 as build-stage

WORKDIR /app

COPY *.json .
RUN npm install

COPY *.config.js .
COPY ./index.html ./index.html
COPY ./src ./src
COPY ./public ./public
RUN npm run build



FROM nginx:1.21.6-alpine AS production-stage

COPY --from=build-stage /app/dist/spa /usr/share/nginx/html

EXPOSE 80
EXPOSE 443
ENTRYPOINT ["nginx", "-g", "daemon off;"]
