services:
  api:
    command: [ "npm", "run", "${ENTRY}" ]
    user: ${TYPE}
    build:
      dockerfile: Dockerfile
      context: .
      target: development-stage-$TYPE-user
      args:
        - UID=$UID
    volumes:
      - .:/api
    ports:
      # api port
      - 3000:3000
      # debugging port
      - 9229:9229
    depends_on:
      - database
    networks:
      - bingewatch-dev-net

  database:
    image: postgres:14.2
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      # database port
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    networks:
      - bingewatch-dev-net

volumes:
  postgres:
    name: database

networks:
  bingewatch-dev-net:
    name: bingewatch-dev-net
