@startuml
class OpinionEntity {
    +id: string
    +authorId: string
    +entryImdb: string
    +replyToId: string
    +text: string
}
class RepositoryService extends PrismaClient {
    -logger: Logger
    +onModuleDestroy(): Promise<void>
    +onModuleInit(): Promise<void>
    +enableShutdownHooks(app: INestApplication): Promise<void>
}
class SecurityService {
    +logger: Logger
    -jwtService: JwtService
    +hashString(data: string): Promise<string>
    +validateAgainstHash(data: string, digest: string): Promise<boolean>
    +checkValidUUID(uuid: string): boolean
    +createJwtFromId(id: string): Promise<string>
}
class UserEntity {
    +id: string
    +role: Role
    +name: string
    +email: string
    +passwordHash: string
}
class SerializedUserEntity {
    +id: string
    +role: Role
    +name: string
    +email: string
}
class EntryEntity {
    +imdbId: string
    +title: string
    +posterUrl: string
    +rating: number
    +seasons: Season[]
    +plot: string
    +rated: string
    +year: string
    +awards: string
    +runtime: string
    +director: string[]
    +writer: string[]
    +actors: string[]
    +genre: string[]
    +language: string[]
}
class Season {
    +episodes: number
}
class EntrySearchResult {
    +imdbId: string
    +title: string
    +posterUrl: string
}
class DetailedWatchlistItemEntity {
    +entry: EntryEntity
    +id: string
    +rating: number
    +progress: number
}
class WatchlistItemEntity {
    +id: string
    +userId: string
    +entryId: string
    +progress: number
    +rating: number
}
class UsersService {
    -repositoryService: RepositoryService
    -securityService: SecurityService
    -logger: Logger
    +findOpinionsByUser(userId: string): Promise<OpinionEntity[]>
    +getWatchlist(userId: string): Promise<WatchlistEntity>
    +isAdmin(id: string): Promise<boolean>
    -create(data: { passwordHash: string; email: string; name: string; }): Promise<UserEntity>
    -findByEmail(email: string): Promise<string>
    +findById(id: string): Promise<UserEntity>
    +getUser(id: string): Promise<UserEntity>
    +changeUserData(id: string, requesterId: string, data: Partial<{ password: string; email: string; name: string; role: Role; }>): Promise<UserEntity>
    +validateCredentials(email: string, password: string): Promise<string | false>
    +register(data: { password: string; email: string; name: string; }): Promise<UserEntity>
    +defaultAdminInit(data: { password: string; email: string; name: string; }): Promise<UserEntity>
}
class OmdbService {
    -logger: Logger
    -httpService: HttpService
    +getEntry(id: string): Promise<OmitNever<Pick<OmitNever<Pick<OmdbMovie & OmdbEpisode, "Title" | "Year" | "Rated" | "Released" | "Runtime" | "Genre" | "Director" | "Writer" | "Actors" | "Plot" | "Language" | ... 9 more ... | "Response">> & OmdbSeries, "Title" | ... 19 more ... | "Response">>>
    +getSeason(id: string, seasonNumber: number): Promise<OmdbSeason>
    +search(query: string, page: number): Promise<OmdbSearchResult>
}
class EntriesService {
    -repositoryService: RepositoryService
    -omdbService: OmdbService
    -logger: Logger
    +findReviewsForEntry(entryId: string): Promise<OpinionEntity[]>
    -getSeason(imdbId: string, seasonNumber: number): Promise<number>
    -getSeasons(imdbId: string): Promise<number[]>
    -create(imdbId: string): Promise<EntryEntity>
    +getEntryByImdbId(imdbId: string): Promise<EntryEntity>
    +refreshRating(imdbId: string): Promise<EntryEntity>
    +refreshData(imdbId: string): Promise<EntryEntity>
    +query(query: string, page: number): Promise<EntrySearchResult[]>
    +getAllIds(): Promise<string[]>
}
class WatchlistService {
    -repositoryService: RepositoryService
    -usersService: UsersService
    -entriesService: EntriesService
    -securityService: SecurityService
    +logger: Logger
    -getItem(id: string): Promise<WatchlistItemEntity>
    +findItemByImdbIdForUser(imdbId: string, userId: string): Promise<WatchlistItemEntity>
    +create(entryId: string, userId: string, requesterId: string): Promise<WatchlistItemEntity>
    +delete(id: string, requesterId: string): Promise<WatchlistItemEntity>
    +updateItem(id: string, requesterId: string, data: Partial<{ rating: number; progress: number; }>): Promise<WatchlistItemEntity>
}
class OpinionsService {
    +logger: Logger
    -repositoryService: RepositoryService
    -watchlistService: WatchlistService
    -usersService: UsersService
    -securityService: SecurityService
    +findRepliesForOpinion(opinionId: string): Promise<OpinionEntity[]>
    +findOpinion(opinionId: string): Promise<OpinionEntity>
    +addReview(authorId: string, entryId: string, text: string): Promise<OpinionEntity>
    +replyToOpinion(opinionId: string, text: string, authorId: string): Promise<OpinionEntity>
    +updateOpinion(opinionId: string, text: string, requesterId: string): Promise<OpinionEntity>
    +deleteOpinion(opinionId: string, requesterId: string): Promise<OpinionEntity>
    +deleteOpinionSafely(opinionId: string): Promise<OpinionEntity>
    -hasUndeletedReplies(opinionId: string): Promise<boolean>
    +getPreservedOpinionsIds(): Promise<string[]>
}
class JwtGuard
class HTTPErrorsService {
    -logger: Logger
    +mapToHTTPError(err: ThrownError): void
}
class AddReviewDto {
    +entryId: string
    +text: string
}
class OpinionContentDto {
    +text: string
}
class OpinionsController {
    -logger: Logger
    -opinionsService: OpinionsService
    -errorsService: HTTPErrorsService
    +getOpinion(id: string): Promise<OpinionEntity>
    +getReplies(id: string): Promise<OpinionEntity[]>
    +addReview(authorId: string, createItemDto: AddReviewDto): Promise<OpinionEntity>
    +addReply(opinionId: string, authorId: string, opinionDto: OpinionContentDto): Promise<OpinionEntity>
    +updateOpinon(opinionId: string, requesterId: string, opinionDto: OpinionContentDto): Promise<OpinionEntity>
    +deleteOpinon(opinionId: string, requesterId: string): Promise<OpinionEntity>
}
EntryEntity --> "*" Season
DetailedWatchlistItemEntity --> "1" EntryEntity
UsersService ..> RepositoryService
UsersService ..> SecurityService
EntriesService ..> RepositoryService
EntriesService ..> OmdbService
WatchlistService ..> RepositoryService
WatchlistService ..> UsersService
WatchlistService ..> EntriesService
WatchlistService ..> SecurityService
OpinionsService ..> RepositoryService
OpinionsService ..> WatchlistService
OpinionsService ..> UsersService
OpinionsService ..> SecurityService
OpinionsController ..> OpinionsService
OpinionsController ..> HTTPErrorsService
@enduml