@startuml functonality

left to right direction


:Neautentificat: as Neautentificat

:Admin: as Admin
:Utilizator: as Utilizator

package "Bingewatch" {

    package "Authentification" {
        "Înregistrare" as (Înregistrare)
        "Autentificare" as (Autentificare)
        "Deconectare" as (Deconectare)

        Neautentificat --> Înregistrare 

        Înregistrare --> Utilizator

        Neautentificat --> Autentificare
        Autentificare --> Utilizator
        Autentificare --> Admin
        
        Utilizator --> Deconectare
        Admin --> Deconectare
        Deconectare --> Neautentificat
    }

    package "Users" {
        "Vizualizare detalii cont" as (AccountDetails)
        "Actualizare detalii cont" as (AccountDetailsUpdate)

        Utilizator --> AccountDetails
        Admin --> AccountDetails

        Utilizator --> AccountDetailsUpdate : Numai daca e contul lui
        Admin --> AccountDetailsUpdate
    }

    package "Entries" {
        "Căutare titula" as (Search)
        "Vizualizare detalii film/serial" as (View)
        "Vizualizare recenzii film/serial și raspunsuri la recenzii" as (ViewReviews)

        Neautentificat --> Search
        Utilizator --> Search
        Admin --> Search

        Neautentificat --> View
        Utilizator --> View
        Admin --> View
        
        Neautentificat --> ViewReviews
        Utilizator --> ViewReviews
        Admin --> ViewReviews
    }

    package "Watchlist" {
        "Vizualizare watchlist și statistici" as (ViewWatchlist)
        "Adăugare film/serial la watchlist" as (AddItem)
        "Elimina film/serial din watchlist" as (RemoveItem)
        "Adauga progres la film/serial" as (AddProgress)
        "Elimina progres la film/serial" as (RemoveProgress)
        "Adauga/Modifica/Sterge calificativ la film/serial" as (Grade)

        Neautentificat --> ViewWatchlist
        Utilizator --> ViewWatchlist
        Admin --> ViewWatchlist

        Utilizator --> AddItem : Numai daca e lista lui
        Admin --> AddItem : Numai daca e lista lui

        Utilizator --> RemoveItem : Numai daca e lista lui și daca nu are o recenzie
        Admin --> RemoveItem : Numai daca e lista lui și daca nu are o recenzie

        Utilizator --> AddProgress : Numai daca e lista lui
        Admin --> AddProgress : Numai daca e lista lui

        Utilizator --> RemoveProgress : Numai daca e lista lui
        Admin --> RemoveProgress : Numai daca e lista lui

        Utilizator --> Grade : Numai daca e lista lui
        Admin --> Grade : Numai daca e lista lui
    }

    package "Opinions" {
        "Adăugare recenzie" as (AddReview)
        "Adăugare raspuns" as (AddAnswer)
        "Editare opinie" as (EditOpinion)
        "Ștergere opinie" as (DeleteOpinion)

        Utilizator --> AddReview : Numai daca are titlul în watchlist
        Admin --> AddReview : Numai daca are titlul în watchlist

        Utilizator --> AddAnswer
        Admin --> AddAnswer

        Utilizator --> EditOpinion : Numai daca e recenzie lui
        Admin --> EditOpinion

        Utilizator --> DeleteOpinion : Numai daca e recenzie lui
        Admin --> DeleteOpinion
    }

    package "Tasks" {
        :Sarcină periodică: as ScheduledTasks

        "Actualizare date filme și seriiale" as (UpdateDate)
        "Actualizare notă medie filme și seriale" as (UpdateAverage)

        ScheduledTasks --> UpdateDate
        ScheduledTasks --> UpdateAverage
     }

}






@enduml