name: ci-backend

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/**"
      - "backend/**"
  push:
    paths:
      - ".github/workflows/**"
      - "backend/**"

jobs:
  ci-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install backend dependencies
        run: npm i
        working-directory: ./backend
      - name: Format backend
        run: npm run format
        working-directory: ./backend
      - name: Lint backend
        run: npm run lint
        working-directory: ./backend
      - name: Build backend
        run: npm run build
        working-directory: ./backend
      - name: Test backend
        run: |
          docker-compose up -d database
          mv example.env .env
          sed -i 's/database/localhost/g' .env
          sed -i 's/OMDB_apikey=""/OMDB_apikey="${{ secrets.OMDB_APIKEY }}"/g' .env
          npx prisma migrate deploy
          npx prisma generate
          npm run test
        working-directory: ./backend
