name: ci-frontend

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/**"
      - "frontend/**"
  push:
    paths:
      - ".github/workflows/**"
      - "frontend/**"

jobs:
  ci-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install frontend dependencies
        run: npm i
        working-directory: ./frontend
      - name: Format frontend
        run: npm run format
        working-directory: ./frontend
      - name: Lint frontend
        run: npm run lint
        working-directory: ./frontend
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend
      - name: Prepare api
        run: |
          mv example.env .env
          sed -i 's/database/localhost/g' .env
          sed -i 's/OMDB_apikey=""/OMDB_apikey="${{ secrets.OMDB_APIKEY }}"/g' .env
          sed -i 's/DEFAULT_ADMIN_NAME=""/DEFAULT_ADMIN_NAME="${{ secrets.ADMIN_NAME }}"/g' .env
          sed -i 's/DEFAULT_ADMIN_PASSWORD=""/DEFAULT_ADMIN_PASSWORD="${{ secrets.ADMIN_PASSWORD }}"/g' .env
          sed -i 's/DEFAULT_ADMIN_EMAIL=""/DEFAULT_ADMIN_EMAIL="${{ secrets.ADMIN_EMAIL }}"/g' .env
          npm i
        working-directory: ./backend
      - name: Test frontend
        run: |
          cd ../backend/ && docker-compose up -d database && (npm run start:development&)
          cd ../frontend/ && npm run test
        working-directory: ./frontend
