name: ci-frontend

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/**"
      - "frontend/**"
  push:
    paths:
      - ".github/workflows/**"
      - "frontend/**"

jobs:
  ci-frontend:
    runs-on: ubuntu-latest
    env:
      DEFAULT_ADMIN_EMAIL: ${{ secrets.DEFAULT_ADMIN_EMAIL }}
      DEFAULT_ADMIN_NAME: ${{ secrets.DEFAULT_ADMIN_NAME }}
      DEFAULT_ADMIN_PASSWORD: ${{ secrets.DEFAULT_ADMIN_PASSWORD }}
      OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install frontend dependencies
        run: npm i
        working-directory: ./frontend
      - name: Install backend dependencies
        run: npm i
        working-directory: ./backend
      - name: Test frontend
        run: make test-root
        working-directory: ./frontend
